# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{awesome_email}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["imedo GmbH"]
  s.date = %q{2010-08-10}
  s.description = %q{Rails ActionMailer with HTML layouts, inline CSS and entity substitution.}
  s.email = %q{entwickler@imedo.de}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.textile",
     "Rakefile",
     "lib/awesome_email.rb",
     "lib/awesome_email/convert_entities.rb",
     "lib/awesome_email/helpers.rb",
     "lib/awesome_email/inline_styles.rb",
     "lib/css_parser/rule_set.rb",
     "rails/init.rb",
     "test/awesome_email_test.rb",
     "test/test-app/README",
     "test/test-app/Rakefile",
     "test/test-app/app/controllers/application_controller.rb",
     "test/test-app/app/helpers/application_helper.rb",
     "test/test-app/app/models/simple_mailer.rb",
     "test/test-app/app/views/layouts/test.html.erb",
     "test/test-app/app/views/simple_mailer/test.text.html.erb",
     "test/test-app/config/boot.rb",
     "test/test-app/config/database.yml",
     "test/test-app/config/environment.rb",
     "test/test-app/config/environments/development.rb",
     "test/test-app/config/environments/production.rb",
     "test/test-app/config/environments/test.rb",
     "test/test-app/config/initializers/backtrace_silencers.rb",
     "test/test-app/config/initializers/cookie_verification_secret.rb",
     "test/test-app/config/initializers/inflections.rb",
     "test/test-app/config/initializers/mime_types.rb",
     "test/test-app/config/initializers/new_rails_defaults.rb",
     "test/test-app/config/initializers/session_store.rb",
     "test/test-app/config/locales/en.yml",
     "test/test-app/config/routes.rb",
     "test/test-app/db/seeds.rb",
     "test/test-app/log/development.log",
     "test/test-app/log/production.log",
     "test/test-app/log/server.log",
     "test/test-app/log/test.log",
     "test/test-app/public/404.html",
     "test/test-app/public/422.html",
     "test/test-app/public/500.html",
     "test/test-app/public/favicon.ico",
     "test/test-app/public/images/rails.png",
     "test/test-app/public/index.html",
     "test/test-app/public/javascripts/application.js",
     "test/test-app/public/javascripts/controls.js",
     "test/test-app/public/javascripts/dragdrop.js",
     "test/test-app/public/javascripts/effects.js",
     "test/test-app/public/javascripts/prototype.js",
     "test/test-app/public/robots.txt",
     "test/test-app/public/stylesheets/test.css",
     "test/test-app/script/about",
     "test/test-app/script/console",
     "test/test-app/script/dbconsole",
     "test/test-app/script/destroy",
     "test/test-app/script/generate",
     "test/test-app/script/performance/benchmarker",
     "test/test-app/script/performance/profiler",
     "test/test-app/script/plugin",
     "test/test-app/script/runner",
     "test/test-app/script/server",
     "test/test-app/test/test_helper.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/grimen/awesome_email/tree/master}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Rails ActionMailer with HTML layouts, inline CSS and entity substitution.}
  s.test_files = [
    "test/awesome_email_test.rb",
     "test/test-app/app/controllers/application_controller.rb",
     "test/test-app/app/helpers/application_helper.rb",
     "test/test-app/app/models/simple_mailer.rb",
     "test/test-app/config/boot.rb",
     "test/test-app/config/environment.rb",
     "test/test-app/config/environments/development.rb",
     "test/test-app/config/environments/production.rb",
     "test/test-app/config/environments/test.rb",
     "test/test-app/config/initializers/backtrace_silencers.rb",
     "test/test-app/config/initializers/cookie_verification_secret.rb",
     "test/test-app/config/initializers/inflections.rb",
     "test/test-app/config/initializers/mime_types.rb",
     "test/test-app/config/initializers/new_rails_defaults.rb",
     "test/test-app/config/initializers/session_store.rb",
     "test/test-app/config/routes.rb",
     "test/test-app/db/seeds.rb",
     "test/test-app/test/test_helper.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["~> 2.3.1"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.3.3"])
      s.add_runtime_dependency(%q<css_parser>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["~> 2.3.1"])
      s.add_dependency(%q<nokogiri>, [">= 1.3.3"])
      s.add_dependency(%q<css_parser>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 2.3.1"])
    s.add_dependency(%q<nokogiri>, [">= 1.3.3"])
    s.add_dependency(%q<css_parser>, [">= 0"])
  end
end

